# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibbonaci_even(limit):
    tmp = 0
    actual = 0
    consequent = 1
    evens = []
    while consequent < limit:
        tmp = consequent
        consequent += actual
        actual = tmp
        if consequent % 2 == 0:
            evens.append(consequent)
    if consequent >= limit and consequent % 2 == 0:
        evens.remove(consequent)
        
    return(sum(evens))

print(fibbonaci_even(4000000))

